import type { Listing } from "./types";

export const dummyListings: Listing[] = [
  {
    id: "1",
    title: "Modern Private Room",
    description:
      "Bright private room in a shared house, freshly renovated with a queen bed and large window.",
    type: "private_room",
    price: { amount: 850, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 1,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    ],
    address: "24 Dunlop Street, Barrie, ON",
    latitude: 44.3891,
    longitude: -79.6893,
    distanceFromCampusKm: 0.8,
    isSaved: false,
  },
  {
    id: "2",
    title: "Downtown Entire Unit",
    description:
      "Fully furnished 2-bedroom apartment steps from downtown Barrie, ideal for two roommates.",
    type: "entire_unit",
    price: { amount: 1650, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 2,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80",
    ],
    address: "58 Collier Street, Barrie, ON",
    latitude: 44.3897,
    longitude: -79.6902,
    distanceFromCampusKm: 0.6,
    isSaved: true,
  },
  {
    id: "3",
    title: "Sunset Shared Room",
    description:
      "Cozy shared room in a quiet 2-bedroom home, great for students on a budget.",
    type: "shared_room",
    price: { amount: 600, currency: "CAD", period: "month", isUtilitiesIncluded: false },
    bedrooms: 2,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    address: "112 Grove Street, Barrie, ON",
    latitude: 44.3925,
    longitude: -79.6811,
    distanceFromCampusKm: 1.1,
    isSaved: false,
  },
  {
    id: "4",
    title: "Cozy Studio Near Campus",
    description:
      "Compact studio unit within walking distance of Georgian College, perfect for one student.",
    type: "entire_unit",
    price: { amount: 1150, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 1,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=800&q=80",
    ],
    address: "9 Essa Road, Barrie, ON",
    latitude: 44.3862,
    longitude: -79.6675,
    distanceFromCampusKm: 0.3,
    isSaved: false,
  },
  {
    id: "5",
    title: "Bayfield Street Room",
    description:
      "Private room with ensuite bathroom in a newly built student house.",
    type: "private_room",
    price: { amount: 950, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 1,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    address: "301 Bayfield Street, Barrie, ON",
    latitude: 44.3781,
    longitude: -79.6835,
    distanceFromCampusKm: 1.4,
    isSaved: false,
  },
  {
    id: "6",
    title: "Wellington 3-Bedroom House",
    description:
      "Spacious entire house with 3 bedrooms, backyard, and driveway parking — great for a group of friends.",
    type: "entire_unit",
    price: { amount: 2400, currency: "CAD", period: "month", isUtilitiesIncluded: false },
    bedrooms: 3,
    furnished: false,
    images: [
      "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80",
    ],
    address: "77 Wellington Street West, Barrie, ON",
    latitude: 44.3839,
    longitude: -79.6902,
    distanceFromCampusKm: 2.1,
    isSaved: true,
  },
  {
    id: "7",
    title: "Anne Street Shared Room",
    description:
      "Shared room in a friendly student household, close to bus routes to campus.",
    type: "shared_room",
    price: { amount: 575, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 2,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80",
    ],
    address: "45 Anne Street South, Barrie, ON",
    latitude: 44.3798,
    longitude: -79.6764,
    distanceFromCampusKm: 1.7,
    isSaved: false,
  },
  {
    id: "8",
    title: "Cundles Road Private Room",
    description:
      "Quiet private room close to Cundles Road, includes access to gym in building.",
    type: "private_room",
    price: { amount: 800, currency: "CAD", period: "month", isUtilitiesIncluded: false },
    bedrooms: 1,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    address: "156 Cundles Road East, Barrie, ON",
    latitude: 44.4012,
    longitude: -79.6721,
    distanceFromCampusKm: 2.6,
    isSaved: false,
  },
  {
    id: "9",
    title: "Bradford Street Entire Unit",
    description:
      "Bright 1-bedroom apartment with in-suite laundry, minutes from downtown.",
    type: "entire_unit",
    price: { amount: 1400, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 1,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    address: "210 Bradford Street, Barrie, ON",
    latitude: 44.3745,
    longitude: -79.6889,
    distanceFromCampusKm: 1.9,
    isSaved: false,
  },
  {
    id: "10",
    title: "Blake Street Shared Room",
    description:
      "Affordable shared room in a 4-bedroom student house, walking distance to campus.",
    type: "shared_room",
    price: { amount: 550, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 4,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    ],
    address: "18 Blake Street, Barrie, ON",
    latitude: 44.3869,
    longitude: -79.6688,
    distanceFromCampusKm: 0.4,
    isSaved: true,
  },
  {
    id: "11",
    title: "Mulcaster Street Loft",
    description:
      "Stylish loft-style unit with high ceilings and exposed brick, close to nightlife on Dunlop.",
    type: "entire_unit",
    price: { amount: 1800, currency: "CAD", period: "month", isUtilitiesIncluded: false },
    bedrooms: 2,
    furnished: true,
    images: [
      "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=800&q=80",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80",
    ],
    address: "63 Mulcaster Street, Barrie, ON",
    latitude: 44.3903,
    longitude: -79.6885,
    distanceFromCampusKm: 0.9,
    isSaved: false,
  },
  {
    id: "12",
    title: "Codrington Street Room",
    description:
      "Private room in a well-maintained home with shared kitchen and living space.",
    type: "private_room",
    price: { amount: 700, currency: "CAD", period: "month", isUtilitiesIncluded: true },
    bedrooms: 1,
    furnished: false,
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    address: "89 Codrington Street, Barrie, ON",
    latitude: 44.3956,
    longitude: -79.6752,
    distanceFromCampusKm: 1.3,
    isSaved: false,
  },
];
